<?php
    try {
        $poshta = $_POST['poshta'];
        $agree = $_POST['agree'];
        $tick = $_POST['tick'];
        $date = $_POST['date'];
    } catch (\Throwable $th) {
        $poshta = "ERROR IN MESSAGE";
        $agree = "ERROR IN MESSAGE";
        $tick = "ERROR IN MESSAGE";
        $date = "ERROR IN MESSAGE";
    }

    $token = "8115391634:AAGFruqcB_zghIYUu0EgkxuM_XiRqrXqPoo"; // Token, generated by Bot Father
    $chat_id = 1911483244; // Number of active chat from https://api.telegram.org/bot7634612042:AAEPXNEI2Qnr0RwW_z5KB57zakFm893lEak/getUpdates

    $textMessage = urlencode("$textMessage");
    // echo("$textMessage");
    $urlQuery = "https://api.telegram.org/bot". $token ."/sendMessage?chat_id=". $chat_id ."&text=". $textMessage . 
        "<b>Ім'я замовника: $userName</b>%0A" .
        "<b>Email замовника: $userEmail</b>%0A" . 
        "<b>Місце проживання: $select</b>%0A" .
        "<b>_________________________</b>%0A" .
        "Дякуємо за відправку заявки"
    ;
    $urlQuery .= "&parse_mode=HTML";
    $result = file_get_contents($urlQuery);
?>